### PR TITLE
Better Travis config

### PR DESCRIPTION
**Pull request by felixfbecker**
See https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

### CODE REVIEW

**Comment by felixfbecker** [comment]
https://travis-ci.org/felixfbecker/Pester/builds/299574193

**Comment by it-praktyk** [comment]
screenshot from 2017-11-09 21-37-56

screenshot from 2017-11-09 21-38-32

**Comment by felixfbecker** [comment]
If you want to point out that this branch took longer, I don't think that is a fair comparison. The upper build was 9 days ago. Time spent waiting in the queue is factored in and Travis had problems yesterday night: https://www.traviscistatus.com/

**Comment by it-praktyk** [comment]
It was just first impression when I cherry-pick'ed your travis.yml. I didn't decide yet.

**Comment by felixfbecker** [comment]
But the container-based builds are actually slower than the VM-based in our case. I just kicked off another build on this branch, maybe you could trigger a build on yours for direct comparison?

**Comment by it-praktyk** [comment]
I did https://travis-ci.org/pester/Pester/builds/299864167?utm_source=github_status&utm_medium=notification

**Comment by felixfbecker** [comment]
So seems like the tests take a lot longer on container-based than on VM-based (599.62s vs 334.72s). I added back `sudo: required`. I still think this travis config is better though because it removes all the `if $TRAVIS_OS_NAME` checks

**Comment by it-praktyk** [comment]
A build time for your config it's about 30% longer than for the current but your travis.yml looks much cleaner.

screenshot from 2017-11-10 08-25-39
screenshot from 2017-11-10 08-26-02

**Pull request merged**
